### ISSUE TITLE
Schiffsnamen Typ

### ISSUE THREAD

**Issue by ChristianReinhard** [OsnaCS/dbp-game#100]
@MarenSteinkamp

Der Typ wenn man ein Schiff erstellt sieht mir nach einem Text aus und nicht nach einem String, somit sind Absätze erlaubt. Könnte man eventuell überdenken.

**Comment by heburke** [comment]
@heburke

**Comment by MarenSteinkamp** [comment]
DONE

**Comment by JulianKniephoff** [comment]
Wo ist der PR dafür? ;)

**Comment by MarenSteinkamp** [comment]
Das war im Pull Request schiff, die zugehörige Migration ist im Haupt Repository schon vorhanden

**Comment by ChristianReinhard** [comment]
@JulianKniephoff könntest das ja mal nachschauen und dann closen. Dann sind wir auf der sicheren Seite!

**Comment by JulianKniephoff** [comment]
Ist tatsächlich vorhanden.
