### ISSUE TITLE
Stationen Upgrade 

### ISSUE THREAD

**Issue by pkechlo** [OsnaCS/dbp-game#102]
@pkechlo @onienhueser
#19 
 Wir kümmern uns um hier um das Upgraden der Stationen.

**Comment by pkechlo** [comment]
Seed.rb für die upgrades angepasst mit migrations.

**Comment by pkechlo** [comment]
- Upgrade-Button steht und an desgin von Forschung angepasst
- Funktionalität Upgrade-Button gegeben
- beides im Pull-Request

**Comment by JulianKniephoff** [comment]
#121 ist gemerged, kann dieser issue dann zu?

**Comment by pkechlo** [comment]
Ja der Issue kann geschlossen werden. Der Upgrade Button mit Funktion für Stationen ist fertig.
