### ISSUE TITLE
Implementation der Einheiten

### ISSUE THREAD

**Issue by Jack5496** [OsnaCS/dbp-game#106]
Da es bereits eine Tabelle aller Einheiten gibt, jedoch keine möglichkeit Einheiten zu genereien/bauen.
Fangen wir an die Seite dafür zu machen

@Jack5496 @AlexanderAltemoeller @NilsAffing

**Comment by Jack5496** [comment]
Update:
- Seite exsistiert mit Auflistung

ToDo:
- Einheiten kaufen können

**Comment by Jack5496** [comment]
Update:
- Multiple Timer
- Maximum der mögl. zu bauenden Truppen
- Einheiten kaufbar

ToDo:
- Maximum der Truppen ändern (Optik)
- Spalte mit "werden gebaut" hinzufügen
- Zeiten zurück auf basis Zeit.
- Werden gebaut muss runtergezählt werden wenn Basiszeit vorbei ist
- Bedingungen für Einheiten fehlen

**Comment by AlexanderAltemoeller** [comment]
Mittlerweile fehlen nurnoch die Bedingungen.
Wir bearbeiten nun die Sciences und auch Units dementsprechend.
Bei den Sciences geht's hier weiter:

**Comment by AlexanderAltemoeller** [comment]
Die grundlegende Implementation der Einheiten ist abgeschlossen.
Damit kann dieses Issue auch geschlossen werden.
