### ISSUE TITLE
Implementierung der anzeige aller Notifications

### ISSUE THREAD

**Issue by ChristianReinhard** [OsnaCS/dbp-game#107]
Ein User soll sich alle seine Notifications anzeigen lassen. Dabei soll er die Nachricht sehen und sie als 'gelesen' makieren können und dabei löschen.

@ChristianReinhard

**Comment by ChristianReinhard** [comment]
@JulianKniephoff PR dafür ist unterwegs #120

**Comment by JulianKniephoff** [comment]
:+1:
