### ISSUE TITLE
`activeShip` benutzerfreundlicher machen

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#109]
Ich hätte gern, dass man statt

```ruby
Ship.find(current_user.activeShip)
```
lieber
```ruby
current_user.active_ship
```
schreiben kann.

@MarenSteinkamp und @heburke, das ist euer Gebiet, oder? Kümmert ihr euch darum?

**Comment by MarenSteinkamp** [comment]
Ich hab eine Methode für das Finden eines Schiffes eingefügt. Pull Request folgt

**Comment by ChristianReinhard** [comment]
@JulianKniephoff müsste laut @MarenSteinkamp fertig sein. Kann also geclosed werden.

**Comment by JulianKniephoff** [comment]
:+1:
