### ISSUE TITLE
Mehrere Timer auf gleicher Seite

### ISSUE THREAD

**Issue by AlexanderAltemoeller** [OsnaCS/dbp-game#115]
Bisher funktioniert der Javascript-Timer nur, wenn nur eine Sache gleichzeitig erforscht/gebaut wird.
Wir bauen nun einen Timer, welcher auch erlaubt mehrere Zeilen gleichzeitig runterzuzählen.

@AlexanderAltemoeller @NilsAffing @Jack5496

**Comment by AlexanderAltemoeller** [comment]
Timer ist im neuen Sciences-PR.
Issue kann also geschlossen werden.

**Comment by JulianKniephoff** [comment]
PR einmal hier verlinken bitte.

**Comment by AlexanderAltemoeller** [comment]
Das ist PR #116.
Liegt also bereits auf dem Master.

**Comment by JulianKniephoff** [comment]
:+1:
