### ISSUE TITLE
Bauplätze Schiffe

### ISSUE THREAD

**Issue by pkechlo** [OsnaCS/dbp-game#122]
Zu den Schiffen müsste das Management bezüglich der Ausbauplätze noch erstellt werden.

**Comment by heburke** [comment]
@heburke @MarenSteinkamp

**Comment by heburke** [comment]
Ausbauplätze werden jetzt bei den Upgrades beachtet. Außerdem haben wir noch einen Downgrade button hinzugefügt. 

Pull request: #157
