### ISSUE TITLE
Energiemanagement Schiffe

### ISSUE THREAD

**Issue by pkechlo** [OsnaCS/dbp-game#123]
Zu den Schiffen müsste das  Energiemanagement noch erstellt werden.

**Comment by pkechlo** [comment]
Wir setzen uns dran:

@pkechlo @onienhueser

**Comment by pkechlo** [comment]
Energieberechnung und -anzeige im Pull Request.

To-Do:

- Ressourcenmalus bei zu hohem Energieverbrauch (https://github.com/OsnaCS/dbp-game/wiki/GameDesign , Management)

**Comment by pkechlo** [comment]
Ressourcenmalus wurde hinzugefügt zum Pull-Request Energy

To-Do:
- Warnung wenn zu viel Energie verbraucht wird bzw. wenn weniger Ressourcen produziert werden

**Comment by pkechlo** [comment]
Wir machen heute die Warnungen.
@pkechlo
@onienhueser

**Comment by pkechlo** [comment]
Außerdem fügen wir jetzt noch einen slider für die Anpassung des Energieverbauchs hinzu.

vgl.: https://github.com/OsnaCS/dbp-game/wiki/Stationen

**Comment by pkechlo** [comment]
Slider wurde hinzugefügt mit Anpassung für Energieverbauch und Ressourcengenerierung. 
Pull-Request: Energy management

To-Do:
- Layout-Anpassung für Slider

**Comment by pkechlo** [comment]
Energieanzeige gefixt.

Wir machen jetzt die Layout-Anpassung für den Slider.
@onienhueser
@pkechlo

**Comment by JulianKniephoff** [comment]
Wie weit seid ihr? Ich höre, ihr spielt nur noch an Slidern rum? ;)
