### ISSUE TITLE
Nicht vorhandene level caps mit nil kodieren, nicht -1

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#125]
@AlexanderAltemoeller in #116 führt ihr eine Methode `has_level_cap` oder so ein, die prüft, ob `level_cap > -1` gilt. Schöner wäre, wenn in der entsprechenden Spalte in der Datenbank bei nicht vorhandenem level cap einfach `nil` (bzw. `NULL` in SQL-Worten) steht, anstatt `-1`. Die Methode könnt ihr euch dann sparen, da `science.level_cap.blank?` einfacher/lesbarer/idiomatischer ist.

Bitte auch in den seeds entsprechend anpassen.

**Comment by AlexanderAltemoeller** [comment]
Wir kümmern uns drum.
Es wird im nächsten PR gefixt sein.

**Comment by JulianKniephoff** [comment]
Lieber wäre mir ein PR, der nur die entsprechenden Änderungen enthält. ;)

**Comment by JulianKniephoff** [comment]
Closed by #132

**Comment by AlexanderAltemoeller** [comment]
#132 
Issue kann also geschlossen werden.
