### ISSUE TITLE
Schiffsbegrenzung durch Forschung

### ISSUE THREAD

**Issue by heburke** [OsnaCS/dbp-game#126]
Einfügen einer Funktion, um dafür zu sorgen, dass nur dann ein weiteres Schiff gekauft werden kann wenn die jeweilige Forschung bereits vorhanden ist.

@heburke @MarenSteinkamp

**Comment by heburke** [comment]
Wurde implementiert und pullrequest steht.

**Comment by JulianKniephoff** [comment]
PR ist #135 (bitte immer Referenzieren ;))

**Comment by ChristianReinhard** [comment]
Da schon gemerged wird geclosed
