### ISSUE TITLE
Vollständige Nachrichten bitte in den Seeds unterbringen!

### ISSUE THREAD

**Issue by ChristianReinhard** [OsnaCS/dbp-game#131]
Jemand möge die Seed datei überarbeiten und für die erstellten Messages einen vollständig grammatikalisch richten Satz für die Spalte `fullmes` mit eingeben. Diese sollen dem User im Notification Center mit dem Format `Ihre Forschung für .... wurde erfolgreich abgeschlossen.`

**Comment by pkechlo** [comment]
@onienhueser @pkechlo
Wir machen das.

**Comment by pkechlo** [comment]
Seed.rb für messages sollte angepasst sein.

**Comment by JulianKniephoff** [comment]
Closed by #138

**Comment by ChristianReinhard** [comment]
Super! Dann erstell doch bitte noch einen PR von einem Branch wo nur die seeds bearbeitet wurde. Das wäre die beste Lösung!

**Comment by JulianKniephoff** [comment]
War irgendwie verwirrt. x)

**Comment by ChristianReinhard** [comment]
Wenns erledigt ist dann closen, wollte nur einen Tipp für den PR geben, ist übersichtlicher als wenn dass irgendwo im nirgendwo mit reinkommt und keiner weiß es

**Comment by ChristianReinhard** [comment]
@pkechlo @JulianKniephoff ist das nun soweit fertig? Oder muss noch was gemacht werden?

**Comment by pkechlo** [comment]
@ChristianReinhard ist angepasst. steht im pull request seed messages

**Comment by ChristianReinhard** [comment]
@pkechlo alles klar!
