### ISSUE TITLE
`activeShip` vs. `active_ship`

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#140]
Jemand durchsuche die code base auf verbleibende Vorkommnisse von Code, der **in etwa** so aussieht:

```ruby
Ship.find(user.activeShip)
```

(Manchmal sieht der auch leicht anders aus, habe ich gesehen, also bitte nicht einfach mit `grep` suchen.)

Sowas kann jetzt dank #113 auch als

```ruby
user.active_ship
```

geschrieben werden. Man hat dann direkt das Schiff in der Hand!

**Comment by arturunios** [comment]
@arturunios @P-Pfeiffer @SebastianRunde

**Comment by JulianKniephoff** [comment]
Habt ihr damit alles erwischt? ;)

**Comment by P-Pfeiffer** [comment]
Sollte alles erledigt sein.
