### ISSUE TITLE
"Globales" Attribut für Spielnamen und eventuell andere Dinge

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#141]
Wäre es nicht irgendwie cool, wenn man in den Views Zugriff auf eine "globale" Variable hätte, die den Spielnamen enthält? Jemand möge mal recherchieren, wo sowas in Rails unterzubringen ist.

Möglich wäre natürlich der `ApplicationController`, aber das finde ich nicht so schön. :/

**Comment by ChristianReinhard** [comment]
@JulianKniephoff ich nehme mich dem an @ChristianReinhard

**Comment by ChristianReinhard** [comment]
@JulianKniephoff ich werde das figaro gem benutzen und dadurch eine config/application.yml bekommen in der man K/V pairs eintragen kann und diese mit ENV["key"] erreichbar sind.

**Comment by JulianKniephoff** [comment]
#156
