### ISSUE TITLE
Routes hat nach aktuellem Stand immer noch Merge Konflikte!

### ISSUE THREAD

**Issue by ChristianReinhard** [OsnaCS/dbp-game#144]
Jemand möge die routes überarbeiten und den vorhandenen Merge Konflikt lösen.

@JulianKniephoff

**Comment by ChristianReinhard** [comment]
@JulianKniephoff habe ich so eben behoben und einen PR dazu erstellt

**Comment by JulianKniephoff** [comment]
#151 ist der PR
