### ISSUE TITLE
Kampfsystem -Berechnung

### ISSUE THREAD

**Issue by AndreasSchroeder** [OsnaCS/dbp-game#145]
Der Ausgang des Kampfes kann nun berechnet werden. 

Noch zu erledigen:
- Mutterschiffe hinzufügen (Stationierte Einheiten und Anlagen)
- Ressourcenberechnung bei erfolgreichen Kampf
- Dauer zum Kampf einfügen
- Einheiten nach Ende in Datenbank schreiben

**Comment by JulianKniephoff** [comment]
Wenn die berechnung des Kampfsystems fertig ist, kann dieses Issue doch eigentlich zu, oder? Bitte für die noch übrigen Aufgaben neue Issues erstellen und heir Referenzieren. ;)

**Comment by AndreasSchroeder** [comment]
#168 in Arbeit

**Comment by AndreasSchroeder** [comment]
to do: #169 Ressourcenberechnung

**Comment by AndreasSchroeder** [comment]
to do: #170 Kampfdauerberechnung

**Comment by AndreasSchroeder** [comment]
#199 Rankberechnung done

**Comment by AndreasSchroeder** [comment]
#201 Restore durch Reperaturgebäude implementiert

**Comment by AndreasSchroeder** [comment]
#202 Schilde werden nun Berechnet

**Comment by AndreasSchroeder** [comment]
#169 implementiert. Ressourcen werden in Flotte gespeichert und können abgefragt werden, wenn diese zurück ist.

**Comment by AndreasSchroeder** [comment]
#202 Spionageevents todo

**Comment by AndreasSchroeder** [comment]
#203 Events für verschiedene Forschungslevel hinzugefügt

**Comment by AndreasSchroeder** [comment]
#204 Schadenstypen müssen noch angepasst werden

**Comment by AndreasSchroeder** [comment]
#204 done

**Comment by AndreasSchroeder** [comment]
Berechnungen soweit abgeschloßen
