### ISSUE TITLE
Implementation Bauliste 

### ISSUE THREAD

**Issue by fizzule** [OsnaCS/dbp-game#147]
Alle aktuellen Bauaufträge von Forschung, Stationen, Anlagen und Einheiten in einer Tabelle vereinen.

**Comment by fizzule** [comment]
@fsandfort, @fizzule

**Comment by fizzule** [comment]
Grundverlinkung zu den facilities ist nun komplett
Es fehlen:
Baulisten abarbeitung bei mehreren aufträgen 
kopieren der verlinkung zu den facilities auf Unit, Research und Station
Überarbeitung der anzeige und ablaufen der gerade herstellenden einheiten und anlagen

**Comment by AlexanderAltemoeller** [comment]
Ich unterstütze heute ebenfalls die Baulistenleute.

@AlexanderAltemoeller

**Comment by JulianKniephoff** [comment]
Wie weit?
