### ISSUE TITLE
GameDesign

### ISSUE THREAD

**Issue by fizzule** [OsnaCS/dbp-game#16]
some stuff

@P-Pfeiffer; @fizzule; @Jack5496; @fsandfort; @SebastianRunde; @arturunios;

**Comment by Jack5496** [comment]
Need:
-Login/Register Seite
-Main Seite

**Comment by Jack5496** [comment]
Login/Register Seite:
Standart Login und Standart Register mit Datenbank verbindung.
Minimal Grafik anpassungen

**Comment by Jack5496** [comment]
Main Seite:
![pjoploo](https://cloud.githubusercontent.com/assets/7412768/9599804/f9fa9e62-5096-11e5-9f9d-22bd309eef84.jpg)

**Comment by Jack5496** [comment]
Spieler Information:
-Name
-Icon/Bild
-Logout

**Comment by Jack5496** [comment]
Spiel-Banner:
-Irgendein tolles Bild oder vorerst einfach als Text
Name: SpielName

**Comment by Jack5496** [comment]
Menü Leiste:
-Rangeliste
-FeatureLiga
-Schiffe
-Forschung
-Stationen
-Anlagen
-Einheiten
-Einstellungen

**Comment by Jack5496** [comment]
Spielkonzept:
-Ein Spieler hat n Forschungen*
-Ein Spieler besitzt 1-9 (Mutter)Schiffe
-Einem (Mutter)Schiff sind zugeordnet 1-n Einheiten
-In einem (Mutter)Schiff liegen 16 Stationen*
-Einheiten unterscheiden sich in Kampf, Resourcen und Spezial Einheiten(z.B. Spionagesonden)

*Anfangs besitzten diese ein Level von 0 und werden später höher.

**Comment by Jack5496** [comment]
ToDo:
- Kosten der Stationen
- Kosten der Forschungen
- Ressourcenproduktion
- Energie Management
- Einheiten(Schiffe) Fluggeschwindigkeit
- Reisezeit Formel
- Eventdesign
- Icons/Bilder**

Done*:
- Schilde
- Treibstoffverbrauch
- Kosten für Einheiten
- Attribute für Einheiten
- Forschungsvorraussetzungen bearbeitet
- Kampfsystem überarbeitet
- Entfernungsformel

*Wird morgen ins Wiki gepostet

**Unter berücksichtung der CC Lizens

**Comment by Jack5496** [comment]
ToDo:
-Komplettes Wiki mit genauen ablauf Aller Abläufe
-Informationstexte der Forschungen und Einheiten

**Comment by JulianKniephoff** [comment]
Was ist hier jetzt noch genau zu tun? Bitte mal in spezifischere issues aufteilen und hier referenzieren. Auch issues, die es schon gibt und die hier zu gehören bitte mal referenzieren.

Alle Informationen aus diesem Issue, die keine Aufgaben sind, die aber nicht weg dürfen, bitte in entsprechende Wiki-Seiten auslagern und diese hier auch referenzieren.
