### ISSUE TITLE
Kampfsystem Berechnung zeit bis Kampf

### ISSUE THREAD

**Issue by AndreasSchroeder** [OsnaCS/dbp-game#170]
Berechnung der Zeit bis zum Kampf muss noch implementiert werden.

Das heißt, die Dauer bis die Schiffe beim Kampf angelangen und den diese für die Rückkehr brauchen.

**Comment by JulianKniephoff** [comment]
Sie auch #210

**Comment by AndreasSchroeder** [comment]
done
