### ISSUE TITLE
Javascript Countdown Timer kaputt

### ISSUE THREAD

**Issue by AlexanderAltemoeller** [OsnaCS/dbp-game#171]
Der Javascript Timer zum Runterzählen der Zeit funktioniert nicht mehr, wenn ein Nutzer während eine Forschungauftrags oder eines Bauauftrages von Einheiten bzw. Gebäuden auf eine andere Seite navigiert.
Sobald der Nutzer, nachdem er auf einer anderen Seite war, zurück zur Seite des Forschungs-/Bauauftrags wechselt, läuft der Timer zu schnell runter.

**Comment by krueter-uos** [comment]
@krueter-uos

Ich übernehme das.

**Comment by ChristianReinhard** [comment]
DOne
