### ISSUE TITLE
Implementation: Forschungen

### ISSUE THREAD

**Issue by SebastianRunde** [OsnaCS/dbp-game#18]
Folgende Forschungen sollten mit den angegebenen Bedingungen und Mechaniken eingebaut werden:

Forschungen sind spielerbezogen und schiffsübergreifend. Sie starten auf Level 0, haben Ressourcenkosten in Mineralien und Kristallen sowie eine Entwicklungszeit. Anfangs kann auf jedem Mutteschiff immer nur eine von den anderen getrennte Forschung entwickelt werden, ein Upgrade schaltet jedoch frei, dass die Forschungseffizenz von mehreren Mutterschiffen kombiniert werden kann (Netzwerktechnologie)
Boni aus mehreren Entwicklungsleveln verhalten sich additiv.
Um Level 1 erforschen zu können, sind teilweise Level auf anderen Forschungen benötigt.

 - Waffenforschungen: 
 -- Laser, +10% Schaden aller Laserwaffen (benötigt Forschungsstation 2, Tier 1)
 -- Ionen, +10% Schaden aller Ionenwaffen (benötigt Laser 10 & Forschungsstation 6, Tier 2)
 -- Kinetik, +10% Schaden aller kinetischen Waffen (benötigt Ionen & Forschungsstation 10 10, Tier 3)

 - Energieschild, +10% zu allen Schildwerten (benötigt Hülle 10, Ionen 2 und Forschungsstation 8, Tier 2)
 - Hülle, +10% zu allen Hüllenwerten (benötigt Forschungsstation 2, Tier 1)
 - Triebwerkstuning, verringert Treibstoffverbrauch der Flugstrecken (benötigt Hülle 4 und Forschungsstation 4, Tier 2)
 - Netzwerktechnologie, pro Stufe kann ein weiteres Mutterschiff an einer Forschung kooperieren (benötigt Spionage 12 und Forschungsstation 12, special tier)
 - Spionage, beeinflusst das Spionage-Event, welches im Kampf auftritt (benötigt Forschungsstation 2, Tier 1)
 - Pilotentraining, beeinflusst Trefferchance während des Kampfes (benötigt Triebwerke 4 und Forschungsstation 8, Tier 3, capped auf 20)
 - Pioniersausbildung, erhöht die maximalanzahl von Mutterschiffen um 1 pro Stufe, capped auf 6. (benötigt Pilotentraining 8 und Forschungsstation 12, special tier)

Forschungszeit: 2 ^ x wobei (x = Tier + aktuelle Stufe - 1) Minuten
Die beiden Forschungen des special tiers haben eine Basiszeit für Stufe 1 von 24 Stunden

**Comment by AlexanderAltemoeller** [comment]
Wir implementieren das!

@NilsAffing @AlexanderAltemoeller

**Comment by SebastianRunde** [comment]
|Forschung|BildURL|
| ---| ---|
|Hülle|![hulle](https://cloud.githubusercontent.com/assets/14051502/9660844/0c8c042c-5258-11e5-8200-163bb640675c.png)|
|Ionen|![ionen forschung](https://cloud.githubusercontent.com/assets/14051502/9660856/1d6f16a8-5258-11e5-99a3-fc08bd0e154f.png)|
|Kinetik|![kinetik forschung](https://cloud.githubusercontent.com/assets/14051502/9660861/2686f2c4-5258-11e5-85bf-dfedc6e41d61.png)|
|Laser|![laser forschung](https://cloud.githubusercontent.com/assets/14051502/9660863/2a779442-5258-11e5-9986-c92366df416d.png)|
|Netzwerk|![netzwerktechnik](https://cloud.githubusercontent.com/assets/14051502/9660865/2ed295be-5258-11e5-90b1-bc6abc9f1501.png)|
|Pilotentraining|![pilotentraining](https://cloud.githubusercontent.com/assets/14051502/9660869/32a3ee0e-5258-11e5-97a1-fda355ae42dc.png)|
|Pioniersausbildung|![pioniersausbildung](https://cloud.githubusercontent.com/assets/14051502/9660871/35c10a40-5258-11e5-9f26-fbd35fced78b.png)|
|Schild|![schild forschung](https://cloud.githubusercontent.com/assets/14051502/9660878/3914a15c-5258-11e5-94b8-8f9b5b026d46.png)|
|Spionage|![spionage](https://cloud.githubusercontent.com/assets/14051502/9660882/3d002ab6-5258-11e5-9d7f-251d0cac83cc.png)|
|Triebwerk|![triebwerk forschung](https://cloud.githubusercontent.com/assets/14051502/9660884/40a1e1b4-5258-11e5-892b-2b7fc791cb0a.png)|

**Comment by AlexanderAltemoeller** [comment]
Forschungen sind voll funktionsfähig.
Stylesheet wird noch angepasst.

@NilsAffing @AlexanderAltemoeller

**Comment by JulianKniephoff** [comment]
Wenn das hier fertig ist, dann könnt ihr mal alle wichtigen Informationen aus diesem Issue in entsprechende Wiki-Seiten auslagern und diese hier referenzieren.

Falls noch irgendwelche spezifische Aufgaben offen sind, bitte neue Issues dafür erstellen und diese hier ebenfalls referenzieren. Falls solche spezifischeren Issues schon existieren, diese bitte auch hier referenzieren.

**Comment by fizzule** [comment]
/ (1 + 0.1 * ShipsStation.find_by(:ship_id => instance.ship_id, :station_id => 2006).level)

**Comment by fizzule** [comment]
2006 is die id für werft bei forschung halt forschungsgebäude

**Comment by AlexanderAltemoeller** [comment]
Irgendwie erscheint mir dieses Issue redundant.
Hier: #53 geht es um dieselbe Thematik. 
Dementsprechend sollte dieses Issue vielleicht geschlossen werden.

**Comment by ChristianReinhard** [comment]
@AlexanderAltemoeller dann schließe ich dass vorerst
