### ISSUE TITLE
Implementation: Stationen

### ISSUE THREAD

**Issue by SebastianRunde** [OsnaCS/dbp-game#19]
Folgende Stationen sollen mit entsprechenden Mechaniken implementiert werden, Namen sind zum aktuellen Zeitpunkt teilweise noch Placeholder.

Mutterschiffe haben einen maximalen Bauplatz von 100. Jedes Level einer Station auf diesem Mutterschiff kostet einen Bauplatz. Sollte der maximale Bauplatz erreicht sein, ist es möglich diesen ein wenig durch Ausbau der Erweiterungsplatform zu erweitern.

Eine Station ist eine Mutterschiff bezogene Aufwertung, welche einen permanenten Effekt auf das entsprechende Mutterschriff hat. Haben ein Level beginnend mit 0 (Sonderregelung:  Scanner für Metalle und Kristalle sowie der Energiegenerator auf Mutterschiffen starten mit 1) und können zu Ressourcenkosten in Metallen und Kristallen aufgewertet werden. Diese Aufwertung dauert jedoch auch eine Bauzeit.

Tier 1 Stationen:

 - Kollektor für die Ressource Metall (passive Erzeugung von Metallen), verbraucht Energie, Energieverbrauch kann mit einem Drosselslider reduziert werden, reduziert analog aber auch die Produktion
 - Kollektor für die Ressource Kristalle (passive Erzeugung von Kristalle), verbraucht Energie, Energieverbrauch kann mit einem Drosselslider reduziert werden, reduziert analog aber auch die Produktion
 - Kollektor für die Ressource Treibstoff (passive Erzeugung von Treibstoff), verbraucht Energie, Energieverbrauch kann mit einem Drosselslider reduziert werden, reduziert analog aber auch die Produktion

 - Lager für die Ressource Metall (Gesamtlagerplatz eines Spielers ergibt sich aus der Summe seiner Lager)
 - Lager für die Ressource Kristalle (Gesamtlagerplatz eines Spielers ergibt sich aus der Summe seiner Lager)
 - Lager für die Ressource Treibstoff (Gesamtlagerplatz eines Spielers ergibt sich aus der Summe seiner Lager)

 - Baugebäude, Aufrüsten erhöht die Geschwindigkeit der Stationsaufrüstung und Anlagen auf diesem Mutterschiff
 - Energiegenerator, produziert Energie, Aufrüsten erhöht die Energiemenge

Tier 2 Stationen:

 - Tresor für die Ressource Metall (Sofern der Spieler einen Angriff auf sein Mutterschiff verliert, bleiben mindestens Ressourcen equivalent zur Kapazität des Tresors erhalten)
 - Tresor für die Ressource Kristalle (Sofern der Spieler einen Angriff auf sein Mutterschiff verliert, bleiben mindestens Ressourcen equivalent zur Kapazität des Tresors erhalten)
 - Tresor für die Ressource Treibstoff (Sofern der Spieler einen Angriff auf sein Mutterschiff verliert, bleiben mindestens Ressourcen equivalent zur Kapazität des Tresors erhalten)
-- Um einen Tresor zu bauen, muss man mindestens das entsprechende Lager auf Stufe 4 oder höher haben.

 - Forschungsstation, Aufrüsten erhöht die Forschungsgeschwindigkeit. 
 -- Bedingung: Baugebäude 4
 - Werft, Aufrüsten erhöht die Konstuktionsgeschwindigkeit von Einheiten in diesem Mutterschiff 
 -- Bedingung: Baugebäude 2
 - Verbrennungsgenerator, produziert Energie, verbraucht dazu Treibstoff, Aufrüsten erhöht die Maximalmenge. Produktionsmenge/Treibstoffverbrauch kann mittels eines Sliders kontrolliert werden.
 -- Bedingung: Energiegenerator 4

Tier 3 Stationen:

 - Reparaturgebäude, stellt nach einem Angriff auf das Mutterschiff einen Anteil der im Kampf zerstörten Anlagen wieder her. Aufrüsten erhöht den Anteil. 
-- Bedingung Baugebäude 8
 - Erweiterungsplatzform, Erhöht die maximalen Bauplätze des Mutterschiffs um 10 pro Upgrade. 
-- Bedingung: Baugebäude 10

Bauzeit der Stationen: 2 ^ x wobei (x = Tier + aktuelle Stufe - 1) Minuten

**Comment by heburke** [comment]
@heburke
@MarenSteinkamp
@pkechlo
@onienhueser
Wir kümmern uns darum ;)

**Comment by heburke** [comment]
Update:
- Tables wurden erstellt und per Join zusammen geführt.
InArbeit:
- Zuordnung der Schiffe zu den zugehörigen Stationen + Speicherung des Levels in passender Tabelle (für den user nicht sichtbar)
 ToDo:
- Layout -> Darstellung der Stationen
- Upgrade-Funktion der Gebäude (Inkl. Kosten, Bauzeit, etc)

**Comment by onienhueser** [comment]
@pkechlo @onienhueser 
Wir erstellen das Layout für die Stationen.

- Reiter für die Schiffe
- Nach Auswahl eines Schiffes werden weitere Links angezeigt: Stationen, Einheiten, ...
- Nach Klick auf Stationen gelang man zu den 16 Stationen und deren Eigenschaften 
(Name, Level, Upgrade-Button)
- Upgrade-Button öffnet neues Fenster mit Kosten und Bauzeit

**Comment by heburke** [comment]
Update2:

- Schiffe werden jetzt automatisch mit den 16 zugehörigen Stationen erstellt

**Comment by pkechlo** [comment]
@onienhueser @pkechlo

Wir erstellen das Layout für die Stationen.

**Comment by heburke** [comment]
DONE:
- Layout ist fertig

TO DO:
- Upgrade der Stationen (warte auf Pull request science)

**Comment by pkechlo** [comment]
@pkechlo @onienhueser
Wir bearbeiten den Upgrade Button, bzw das Upgradeverhalten von Stationen.

**Comment by JulianKniephoff** [comment]
Am besten neue issues für noch offene, spezifische Unteraufgaben erstellen und diese hier referenzieren.

Alle wichtigen Informationen, die noch in diesem Issue enthalten sind, aber keine Aufgaben sind, bitte in entsprechende Wiki-Seiten auslagern und diese hier auch referenzieren.

**Comment by pkechlo** [comment]
Die Informationen aus diesem Issue sind nun im Wiki unter Stationen. (erster Eintrag hier)

**Comment by JulianKniephoff** [comment]
Bitte einmal einen Link auf die entsprechenden Seiten heir hin schreiben.

Und zumindest eine Teilaufgabe hiervon ist jetzt also noch #102, richtig?

Gibt es noch mehr? Ansonsten schließe ich dieses issue jetzt. ;)

**Comment by pkechlo** [comment]
Wiki Seite Stationen: https://github.com/OsnaCS/dbp-game/wiki/Stationen
Übrig gebliebene Aufgabe die hier festgehalten wurde ist nur der Upgrade Button. Dieser befindet sich nun bei #102 
Das issue kann also geschlossen werden.

**Comment by JulianKniephoff** [comment]
:+1:
