### ISSUE TITLE
Form Tag sichern

### ISSUE THREAD

**Issue by fizzule** [OsnaCS/dbp-game#208]
Man müsste am besten noch iwo ne methode machen, die prüft, ob man admin ist und die als before action im zweifelsfall redirected to :back. Das müsste dann in alle Form htmls, weil im Moment kann man einfach in der URL Leiste eine Id eingeben(beginnen oft bei 1) und dahinter /edit und kann dann frei alle werte verändern

**Comment by JulianKniephoff** [comment]
Sollte einfach sein, siehe hier:
https://github.com/OsnaCS/dbp-game/wiki/Benutzerrechte-Accessor

**Comment by ChristianReinhard** [comment]
Letztendlich ist das aber egal für die Funktionalität als solches. Meiner Meinung nach sollte jeder seine eigenen Forms abfragen und sichern. In meinen ist es sogar vorhanden

**Comment by MarenSteinkamp** [comment]
@MarenSteinkamp @heburke
Wir haben Ships_Stations und Stations abgesichert
Pull Request #225
