### ISSUE TITLE
Flottenmanagement

### ISSUE THREAD

**Issue by AlexanderAltemoeller** [OsnaCS/dbp-game#210]
Verwaltung der Flotte, Angriffe, Transporte etc
Aktuelle Missionen: Angriff, Transport und Stationierung

ToDo:
- Parameterüberprüfung
- Man sollte sich nicht selbst angreifen
- Flugzeiten
- Treibstoffverbrauch

Autor: Nils Affing

@NilsAffing @P-Pfeiffer

**Comment by JulianKniephoff** [comment]
Sagt mal, wie weit das jetzt ist.

**Comment by AlexanderAltemoeller** [comment]
Bisher klappt alles.

Was noch fehlt:
Notifications
Kampfmethode
