### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#22]
Bitte benutzt das Issue-System, um zu dokumentieren, was ihr tut, ich sage da noch mal etwas mehr zu, wenn ich wieder da bin (hoffentlich morgen). Also offensichtlich sind zumindest einige gerade mit account management beschäftigt, wer gehört da alles zu außer @ChristianReinhard?

Was ist da jetzt noch genau zu tun? Tragt das mal hier ein.

Wenn da kleinere Aufgabenpakete auszumachen sind, erstellt auch ruhig weitere Issues.

**Comment by krueter-uos** [comment]
@krueter-uos @ChristianReinhard  

Anpassung des Logins.
Verknüpfung der Datensätze.

**Comment by ChristianReinhard** [comment]
Stand Donnerstag 03.09.15(@ChristianReinhard s Fork):

Benutzer können Accounts erstellen (Username, Email, Passwort)
User können sich mit Email oder Username und Passwort einloggen
Alle relevanten Abfragen sind möglich um benutzerspezifisch Informationen darzustellen
Login Formular im "top left" div eingebunden
Edit Account mit Account delete
Views können angepasst werden oder im Application Layout eingebunden werden.

**Comment by ChristianReinhard** [comment]
Ich denke, dass dieses Issue soweit abgeschlossen ist. Das Management wurde auf mehrere Issues aufgeteilt. Zudem ist das Management vorerst fertiggestellt und Du @JulianKniephoff könntest dieses Issue schließen.

**Comment by JulianKniephoff** [comment]
@ChristianReinhard Bitte einmal zu Doku-Zwecken die Issues, in die dieses aufgeteilt wurde, hier referenzieren (mit der #-Syntax).

**Comment by ChristianReinhard** [comment]
#46 #60 #65 müssten alle Abhängigkeiten abdecken.

**Comment by JulianKniephoff** [comment]
:+1:
