### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by krueter-uos** [OsnaCS/dbp-game#23]
Erstellung des User Interfaces. Grobes Spiel-Design.

@krueter-uos @ChristianReinhard

**Comment by ChristianReinhard** [comment]
Stand 02.09.15 (@krueter-uos' Fork)

UI wurde überarbeitet, Platzhalter eingefügt.
Menu derzeit statisch

**Comment by JulianKniephoff** [comment]
Was ist hier jetzt noch genau zu tun? Bitte einmal in spezifischere Issues aufteilen und die hier erwähnen.

**Comment by ChristianReinhard** [comment]
Ansich ist alles fertig. Das einzige was zutun wäre ist, dass Layout und Features regelmäßig designed werden müssen.

**Comment by JulianKniephoff** [comment]
Alles klar.
