### ISSUE TITLE
Kampfsystem

### ISSUE THREAD

**Issue by arturunios** [OsnaCS/dbp-game#24]
Kampfablauf
1.Phase: Spionagephase
- Verteidigende Armee feuert einmal auf angreifende Spionagesonden (weitere angreifende Schiffe werden in dieser Phase ignoriert)
- Trefferchance ist abhängig von Spionageforschungsunterschied der beiden Spieler
- Leben noch angreifende Spionagesonden, dann wird ein Spionage-Event gestartet
- Die angreifende Spionagesonden verlassen den Kampf und fliegen zurück

2.Phase: Schildphase I
- X entspricht der Anzahl der angreifenden EMP-Schiffe mit der Formel (1-1/(x*0.1+1))*0.5 wird die Trefferwahrscheinlichkeit (0.1) bestimmt
- Trifft das EMP-Schiff, fällt das Schild der Verteidiger auf 0

3.Phase: Schildphase II
-  Phase 2 analog für Verteidiger

4.Phase: Angriffsphase
- Angreifer beginnen
- Trefferchance auf eine Zielgruppe ist proportional Abhängig von der Gruppe der Zielhülle von der Gesamthülle der Angreifer/ Verteidiger. Der Zufallstrefferwurf würfelt von 0 bis 1+"Misschance"
Jeder roll über 1 ist automatisch ein "Miss"
- Jede Einheitsgruppe schießt random auf eine Zielgruppe, wobei „Miss“ eine weitere Zielgruppe ist. Bei einem Treffer wird die Schadenssumme der Angreifer und die Hülle der Getroffenen so verrechnet, dass je ein Schiff von 100% auf 0 durch fokussiert wird
- Solange Schild aktiv, bestehen die Zielgruppen nur aus „Miss“ und „Schild“, danach kommen alle Streitkräfte hinzu. Hinzufügen der weiteren Streitkräfte nur nach einer vollendeten Runde
- Overkill einer Zielgruppe wird nicht berücksichtigt
- Abwechselnd beginnt nun der Verteidiger mit Phase 4 
- Kampfabbruch bei zu langen Kämpfen (Unentschieden)
- Misschance 30% - 1% pro Pilotentraining (Bei Schildphase halbiert)

**Comment by AndreasSchroeder** [comment]
@AndreasSchroeder @dbarthol

**Comment by AndreasSchroeder** [comment]
Erledigt:
Views, Models und Controller für "fight", "fighting_fleet" und "fhip_group" wurden erstellt und mit Assoziationen verbunden.
Es ist möglich Kämpfe zu erstellen, die einen Angreifer und einen Verteidiger haben. Es können Schiffsgruppen zu erstellen (Anzahl von Schiffen des selben Typs) und diese einer Flotte zuzuweisen.

In Arbeit:
-Die nötigen Methoden für die Berechnung des Kampfes werden gerade implementiert. (Anhand von harten Daten, noch keine Verbindung mit Tabellen.
-Es wird an der View von Fight gearbeitet. Es soll ein Formular entstehen, indem man alle seine Schiffstypen mit Anzahl sieht. Außerdem hat man die Möglichkeit festzulegen, wie viele Einheiten jeden Typs man für den Angriff auswählt.


Noch zu erledigen:
- Kampfablauf (Methoden in fight) fertigstellen (dynamisch anhand von Werten aus Tabelle)
- Kampfablauf (Methoden in fighting_fleet) fertigstellen
- Kampfablauf (Methoden in ship_groups) fertigstellen
- Kämpfe mit angemeldetem Benutzer verbinden
- Berichte für Kämpfe automatisiert erstellen
- Validierungen einfügen
...
...
- Hilfsmethoden zum testen wieder entfernen (Hardcoding)
- Testen

**Comment by AndreasSchroeder** [comment]
Erledigt:
- Views, Models und Controller für "fight", "fighting_fleet" und "fhip_group" wurden erstellt und mit Assoziationen verbunden.
- Es ist möglich Kämpfe zu erstellen, die einen Angreifer und einen Verteidiger haben. Es können Schiffsgruppen  erstellt (Anzahl von Schiffen des selben Typs) und diese einer Flotte zuzugewiesen werden.
- Formular zum Erstellen von Flotten mit Gruppen und zuweisung zu Kampf

In Arbeit:
- Die nötigen Methoden für die Berechnung des Kampfes werden gerade implementiert. (Anhand von harten Daten, noch keine Verbindung mit Tabellen.)
- Verbindung des Formular mit dem eingeloggten User


Noch zu erledigen:
- Kampfablauf (Methoden in fight) fertigstellen (dynamisch anhand von Werten aus Tabelle)
- Kampfablauf (Methoden in fighting_fleet) fertigstellen
- Kampfablauf (Methoden in ship_groups) fertigstellen
- Kämpfe mit angemeldetem Benutzer verbinden
- Berichte für Kämpfe automatisiert erstellen
- Validierungen einfügen
...
...
- Hilfsmethoden zum testen wieder entfernen (Hardcoding)
- Testen

**Comment by JulianKniephoff** [comment]
Am besten einmal diesen Issue in mehrere, spezifische Issues aufteilen und diese dann hier referenzieren.

Wichtige Informationen, die ihr hieraus noch behalten wollt, bitte ins Wiki übertragen und die entsprechenden Seiten auch hier verlinken.

**Comment by AndreasSchroeder** [comment]
#145 Kampsystem Berechnung

**Comment by JulianKniephoff** [comment]
Sind die wichtigen Informationen auch schon extrahiert? Dann kann ich das ja jetzt zu machen, oder? ;)

**Comment by AndreasSchroeder** [comment]
#146 ist größenteils abgeschlossen

**Comment by AndreasSchroeder** [comment]
#205 Kampfsystem muss noch debuggt werden

**Comment by AndreasSchroeder** [comment]
#205 done

**Comment by AndreasSchroeder** [comment]
#227 Views angepasst

**Comment by AndreasSchroeder** [comment]
#228 Muss noch erledigt werden
