### ISSUE TITLE
GameDesign - Schiffe Attribute 

### ISSUE THREAD

**Issue by arturunios** [OsnaCS/dbp-game#26]
Basisbauzeit = Gesamtkosten * 2 min
Treibstoffverbrauch = [Abstandsmaß] * ([Hüllenmaße] + [Frachtraum])
Geschwindigkeit 8 = 1h Mindestdauer

!Achtung Tabelle geht nach rechts weiter!

Einheit|Metall (Faktor 500)|Kristall (Faktor 500)|Treibstoff (Faktor 500)|Gesamtkosten|Beschreibung| Hülle (Faktor 1000)| Angriff (Faktor 10)|Frachtraum (Faktor 100)|Geschwindigkeit|
--------- | ------------ | ------- | --------- | -----------------|-------|---------|-------|---------|---------------|------|---|
Wertrate|1|2|4
Raketenwerfer|2|||2|Standart Anlage|2|1||
Spionagedrohne|2|||10|Bringt information über Gegner|1||1|128|
mob. Schildgenerator||4|1|8|Schützt eigene Einheiten|5|||4|
Schild klein|50|100||250|Schützt eigenes Schiff|100||
Schild groß|200|400||1000|Schützt eigenes Schiff|500||
EMP-Schiff||400|100|800|möglichekit im Kampf Schild zu zerstören|100|20|120|1|1|
Bombenteleporter||250|100|650|Bonus gegen orbitale Waffenplattform. |100|50|100|1|1|
Transporter klein|5|2||9|Ressourcen transport|2||80|4|4|
Transporter groß|20|8||36|Ressourcen transport|8||400|8|8|
Expeditionsschiff|40||10|80|Bringt event bei Aussenden|50|2|400|8|
Jäger|2|1||4|LASER|1|1|2|8|8|
Fregatte|20|10||40|LASER|10|12|5|8|8|
Kreuzer|20|40||100|ION|10|50|8|4|4|
Zerstörer|200|100||400|KINETIK|200|500|20|4|4|
Bomber|20||10|60|KINETIK|20|10|5|1|4|
Solarpanel||2|1|8|erhöht Energie|1||
Lasergeschütze klein|3|1||5||2|2|
Lasergeschütze groß|12|4||20||10|10|
Ionenbeschleuniger klein|2|3||8||4|4|
Ionenbeschleuniger groß|8|12||32||20|20|
Massenbeschleuiniger|80|20||120||80|80|
orbitale Waffenplattform|100||200|1800||1000|10000|
Geheimwaffe||500|1000|5000|???|2000|1|

**Comment by JulianKniephoff** [comment]
Sind hier jetzt noch wichtige Informationen drin, die noch nicht im Wiki sind? Wenn nicht bitte einmal dahin übertragen und entsprechende Seiten hier referenzieren.

**Comment by heburke** [comment]
Ist in der Wiki mit allen Informationen vorhanden 
[Einheiten](https://github.com/OsnaCS/dbp-game.wiki.git)

**Comment by JulianKniephoff** [comment]
:+1:
