### ISSUE TITLE
Wiki-Seiten zu Workflow und anderen Dingen

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#32]
Jemand mache aus dem Vortrag und [meinen Vortragsnotizen](https://github.com/OsnaCS/dbp-game/wiki/Vortrag) noch vernünftige Wiki-Seiten

**Comment by heburke** [comment]
[Workflow](https://github.com/OsnaCS/dbp-game/wiki/Workflow)
