### ISSUE TITLE
GameDesign - Forschung Stats

### ISSUE THREAD

**Issue by arturunios** [OsnaCS/dbp-game#35]
|Forschung|Kosten Metall|Kosten Kristall|Kosten Treibstoff|Gesamtsumme|
|--------------|-------------|------------|-----------|--------------------|
|Hülle|10|||10|
|Laser|4|3||10|
|Spionage||3|1|10|
|Triebwerk|8||3|20|
|Ionen|4|8||20|
|Schilde||6|2|20|
|Pilotentraining|20||5|40|
|Netzwerk||160|100|720|
|Pionierausbildung|320||100|720|
|Kinetik|20|10||40|

**Comment by JulianKniephoff** [comment]
Sind hier jetzt noch wichtige Informationen drin, die noch nicht im Wiki sind? Wenn nicht bitte einmal dahin übertragen und entsprechende Seiten hier referenzieren.

**Comment by AlexanderAltemoeller** [comment]
Der entsprechende Wikieintrag liegt hier:
https://github.com/OsnaCS/dbp-game/wiki/Forschung

Die Implementationsupdates sind in diesem Issue: #53

**Comment by ChristianReinhard** [comment]
@AlexanderAltemoeller fertig und closed
