### ISSUE TITLE
GameDesign - Stationen Stats

### ISSUE THREAD

**Issue by arturunios** [OsnaCS/dbp-game#36]
|Station|Kosten Metal.|Kosten Kristall.|Kosten Treibstoff.|Gesamtkosten|
|---------|-------------|------------|------------|-------------------|
|Scanner Metall|4|1||6|
|Scanner Kristall|2|2||6|
|Scanner Treibstoff|2||1|6|
|Forschungsstaion||2|1|8|
|Baugebäude|2|1||4|
|Werft|4||1|8|
|Erweiterungsplattform|8||2|16|
|Ressourcenlager Metall|3|1||5|
|Ressourcenlager Kristall|1|2||5|
|Ressourcenlager Treibstoff|1||1|5|
|Ressourcentresor Metall|6|2||10|
|Ressourcentresor Kristall|2|4||10|
|Ressourcentresor Treibstoff|2||2|10|
|Energiegenerator||1|1|6|
|Verbrennungsgenerator|4||1|8|
|Reparaturgebäude|8|4||16|

**Comment by JulianKniephoff** [comment]
Sind hier jetzt noch wichtige Informationen drin, die noch nicht im Wiki sind? Wenn nicht bitte einmal dahin übertragen und entsprechende Seiten hier referenzieren.

**Comment by heburke** [comment]
[Stationen](https://github.com/OsnaCS/dbp-game.wiki.git)

**Comment by JulianKniephoff** [comment]
:+1:
