### ISSUE TITLE
Expeditionsevents

### ISSUE THREAD

**Issue by Jack5496** [OsnaCS/dbp-game#39]
-nichts
-kampf
-zerstörung
-bergen
-Ressourcen

**Comment by Jack5496** [comment]
Nichts:
-Deine Einheiten haben nur die weite des Weltraumes gesehen und kamen zurück.
-Deine Einheiten haben haben ein Dokument gefunden, allerdings ist es mit Milch durchweicht wodurch es unleserlich wurde.
-Deine Einheiten haben einen kleinen Stop bei SpaceBurger gemacht und kamen gesättigt zurück.
-Deine Einheiten bewunderten einige exotische Planeten.
-Deine Einheiten haben einige friedliche Schiffe entdeckt und kamen unversehrt zurück.

**Comment by P-Pfeiffer** [comment]
-kampf
Auf seiner Reise fiel deine Expedition in die Hände berüchtigter Weltraumpiraten.

Deine Einheiten landeten auf ihrer Reise im Orbit eines unbekannten Planeten, auf dem sie Eingeborene trafen. Aufgrund eines kulturellen Missverständnisses kam es zu einer Schlacht zwischen den Parteien.

Deine Einheiten trafen auf ein Volk, dass aufgrund eines traumatischen Erlebnisses darüber erzürnt war, dass die Crew Milch bei sich hatte. Es kam zur Schlacht.

Deine Einheiten trafen auf eine Crew eines verfeindeten Mutterschiffes. Es kam zur Auseinandersetzung.

**Comment by Jack5496** [comment]
Zerstörung:
-Keine deiner Einheiten kamen zurück, es wurden lediglich Trümmer gefunden.
-Deine Einheiten haben einen katastrophalen Unfall gehabt ... vielleicht Wildwechsel?
-Deine Einheiten haben einen Verkehrsunfall gehabt. Ihnen wurde die Vorfahrt genommen ... wobei jeder weiß, dass man Vorfahrt hat wenn man nett lächelt und winkt.
-Deine Einheiten haben bekanntschaft mit einem Asteroiden gemacht ... von nahem.
-Deine Einheiten wurden von einem SpaceShark gefressen, leider hört man im Luftleeren Raum das JawTheme nicht.

**Comment by P-Pfeiffer** [comment]
Deine Einheiten fanden eine verlassene Zivilisation. Sie nahmen Schiffe und goldene Tierstatuen mit.

Deine Einheiten nahmen an einer intergalaktischen Auktion statt und haben ein paar Schiffe ersteigert. Zum Glück waren Steine die örtliche Währung.

Deine Einheiten fanden ein verlassenes Mutterschiff. Sie nahmen die brauchbaren Schiffe mit.

Deine Einheiten schlossen sich einem Krieg gegen einen Imperator an und gewannen. Aus Dankbarkeit erhielten sie Schiffe.

Deine Einheiten fanden ein verlassenes Schiffslager und plünderten es.

**Comment by Jack5496** [comment]
Ressourcen:
-Deine Einheiten durchkämmten die Wüste (mit einem Kamm) und fanden dabei einige lohnende Ressourcen
-Deine Einheiten fanden einen unbewohnten Planten mit vielen Ressourcen
-Deine Einheiten H4-N5 flogen mit Gold los um neue Güter zu ertauschen, und erhielten zuerst Pferde welche sie dann weiter eintauschten, Schweine erhielten sie aber nicht.
-Deine Einheiten kamen an einem intergalaktischen Kirmes vorbei und gewannen bei dem Spiel "Wirf de Ringe um den Saturn" einige wertvolle Ressourcen.
-Deine Einheiten trafen auf ein Transportschiff und beuteten dieses aus ... sie fühlten sich dabei schlecht, da sie ihre Freibeuter Liezens nicht dabei hatten.

**Comment by ChristianReinhard** [comment]
Wenn ich grad so fleißig dabei seid, wäre es gut wenn ihr auch gleich Euch die Nachrichten Codes mit ausdenkt, damit wird später die Nachrichten richtig verknüpfen können. Als weit bekanntes Beispiel: 404 - Not Found Error. Danke

**Comment by ChristianReinhard** [comment]
Wir fangen auch schon mal an die Relationen etc. zu erstellen

**Comment by P-Pfeiffer** [comment]
Wir implementieren die Expiditionsevents.

@arturunios @P-Pfeiffer

**Comment by ChristianReinhard** [comment]
Eigentlich ist soweit alles vorhanden, zumindest hatte ich versucht, das mitzuteilen, als ich in dem Stand Up davon gesprochen hatte, das die Notifications funktionieren, was fehlt sind die Datensätze in einer Datenbank, bzw. besser ein Script das die Daten in eine Datenbank lädt.

**Comment by JulianKniephoff** [comment]
Alles klar, also wartet ihr auf #48, richtig?

**Comment by ChristianReinhard** [comment]
Ich denke, dass #48 die Datensätze beinhaltet.

**Comment by P-Pfeiffer** [comment]
Was wir implementieren ist der Code hinter den Notifications, also das, was im Hintergrund auf den Expeditionen geschieht.

**Comment by JulianKniephoff** [comment]
Bitte teilt das mal in spezifischere issues auf und referenziert die hier.

Alle wichtigen Informationen, die hier drin sind und die ihr behalten wolltet, übertragt ihr bitte in entsprechende Seiten ins Wiki, die ihr dann auch hier verlinkt.
