### ISSUE TITLE
Fehler, wenn nicht eingeloggt

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#41]
Ihr müsst aufpassen, dass die App nicht crasht, wenn ich nicht eingeloggt bin und eine Seite besuche, die ich dann eigentlich nicht sehen darf.

**Comment by krueter-uos** [comment]
Auf welche Seiten trifft das denn hierbei zu?

**Comment by JulianKniephoff** [comment]
Das ist Teil der Aufgabe, das rauszukriegen. ;)

**Comment by JulianKniephoff** [comment]
Ist das jetzt für alle Seiten gelöst? Wenn ja, bitte einmal die Lösung hier beschreiben. Falls nicht, möge sich mal jemand die Mühe machen, das bei allen Seiten zu probieren und entsprechende Issues aufzumachen und die dann hier zu verlinken.

**Comment by ChristianReinhard** [comment]
@JulianKniephoff theoretisch sollte das passen wir haben die before action ja im application controller eingefügt somit könnte das geclosed werden.

**Comment by ChristianReinhard** [comment]
@JulianKniephoff das hängt noch mit in einem PR von @MarenSteinkamp

**Comment by JulianKniephoff** [comment]
Welcher PR ist das?

**Comment by MarenSteinkamp** [comment]
#118
