### ISSUE TITLE
Layout geht bei Falscheingaben kaputt

### ISSUE THREAD

**Issue by fsandfort** [OsnaCS/dbp-game#47]
Wenn man bei der Registrierung ein zu kurzes Passwort eingibt, oder man das Passwort mit dem zweiten Feld falsch bestätigt, dann rutscht das Feld an den linken Rand des Layouts und sieht kaputt aus.
Zudem haben wir den Fehler auch in der Forschung festgestelt, nachdem wir eine Namensvalidierung ergänzt haben und diese getestet haben. Daher gehen wir davon aus, dass das ein allgemeines Problem im Layout ist.

**Comment by JulianKniephoff** [comment]
Das hat mit den Validations zu tun. Jemand muss rauskriegen, wie man die mit CSS stylen kann.

**Comment by krueter-uos** [comment]
Ist gefixt.

**Comment by AlexanderAltemoeller** [comment]
Die Textfelder springen zwar nichtmehr an komische Positionen bei Falscheingaben, aber die standartiesierte Rails-Fehlermeldung sieht nach wie vor noch kaputt aus.

**Comment by ChristianReinhard** [comment]
Kann man überarbeiten, hat aber keine Priorität.

**Comment by JulianKniephoff** [comment]
Jemand möge nochmal systematisch untersuchen, wo das noch passiert und dann neue issues aufmachen. Und dann verlinkt die bitte hier.

**Comment by ChristianReinhard** [comment]
Wurde behoben
