### ISSUE TITLE
Seed-Daten

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#48]
Es gibt ja so "Referenz-Tabellen" wie `sciences`, die sich während des Spiels eigentlich nicht ändern. Diese will man beim Testen oder Deployen nicht jedes mal neu Einpflegen, also muss jemand ein Skript oder sowas ähnliches schreiben, was diesen Schritt automatisiert.

Stichwörter, die ihr da mal recherchieren könnt ist:
- Rails seed data
- Vielleicht kann man auch fixtures dafür benutzen.

Interessant, aber erstmal nicht so wichtig, ist dann noch der umgekehrte Schritt: Wenn man diese Tabellen jetzt doch aus der App heraus bearbeitet, wie kann man dann irgendwie automatisiert aus den Tabellen dieses Seed-Skript erstellen.

**Comment by pkechlo** [comment]
@onienhueser @pkechlo

Wir machen die seed Datei für die Stationen.

**Comment by AndreasSchroeder** [comment]
@andschroeder

Ich mache die Seeds für die Schiffe

**Comment by pkechlo** [comment]
Update Stationen:

seeds.rb ist fertig erstellt.

**Comment by AlexanderAltemoeller** [comment]
Wir übernehmen die Seeds für Forschung.

@AlexanderAltemoeller @NilsAffing @fsandfort @fizzule

**Comment by AndreasSchroeder** [comment]
@AndreasSchroeder, @dbarthol

**Comment by AlexanderAltemoeller** [comment]
Forschungs-Seeds sind fertig
@AlexanderAltemoeller @NilsAffing @fsandfort @fizzule

**Comment by JulianKniephoff** [comment]
Bitte einmal eine Zusammenfassung, welche Seeds jetzt noch fehlen?
Und habe ich die schon alle im `master`?

**Comment by pkechlo** [comment]
Die seeds.rb für Stationen liegt noch im PullRequest zu StationLayout.

**Comment by pkechlo** [comment]
@pkechlo @onienhueser

Wir machen die seeds.rb für Messages.

**Comment by pkechlo** [comment]
seeds.rb für Messages und Stations ist soweit fertig.

**Comment by fsandfort** [comment]
seeds für den Handelsbasar sind auch fertig

**Comment by JulianKniephoff** [comment]
Bitte erstellt mal Issues für alle seed-Arten, die jetzt noch offen sind.

**Comment by ChristianReinhard** [comment]
#179
