### ISSUE TITLE
Datenbank-Schema

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#49]
Irgendwo sollte ein oder mehrere ER-Diagramme liegen, die das Datenbank-Schema beschreiben.

Das muss jetzt nicht ein riesiges Bild sein, sondern kann sich auf bestimmte Aspekte des Systems einschränken, z.B. "User und all seine (direkten) Relationships". Dann sollten alle diese Bilder zusammen allerdings das ganze System beschreiben.

**Comment by ChristianReinhard** [comment]
@JulianKniephoff mache ich morgen. @ChristianReinhard

**Comment by krueter-uos** [comment]
ER-Diagramm wurde erstellt.

#209
