### ISSUE TITLE
JavaScript für timer, etc.

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#52]

**Comment by Jack5496** [comment]
Sind dabei @Jack5496 @AlexanderAltemoeller

**Comment by Jack5496** [comment]
Dropped, da zu viel Aufwand für zu minimales Feature --> vlt später

**Comment by Jack5496** [comment]
Tolle neue Infos/Tutorial hier:
http://stackoverflow.com/questions/26954244/ruby-on-rails-html-table

**Comment by NilsAffing** [comment]
@NilsAffing

**Comment by Jack5496** [comment]
Update:
- Zeit zählt runter
- Fomat ist passend
-Seite updated automatisch nach erreichen des Ende

ToDo:
- mögliche Fehlermeldungen
- Auslagern der Javascript function

**Comment by Jack5496** [comment]
=CLOSED=

**Comment by JulianKniephoff** [comment]
Wo ist der PR hierfür? ;P

**Comment by AlexanderAltemoeller** [comment]
Ist bereits auf dem master und gemerged.
Issue kann also geschlossen werden.

**Comment by Jack5496** [comment]
Issue nicht schließen

ToDo:
- Ressourcen mittels Javascript automatisch updaten

**Comment by ChristianReinhard** [comment]
@krueter-uos und @ChristianReinhard haben weitere JS Timer implementiert, die sowohl Resourcen als auch Notifications updaten.
