### ISSUE TITLE
Implementation der Forschung

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#53]

**Comment by fsandfort** [comment]
@AlexanderAltemoeller @NilsAffing @fsandfort

**Comment by AlexanderAltemoeller** [comment]
Game-Icons werden hinzugefügt

@AlexanderAltemoeller @NilsAffing @fsandfort

**Comment by Jack5496** [comment]
Update:
- Timer works
- Seeds included
- Icons added
- Costs formular added

@AlexanderAltemoeller @NilsAffing @Jack5496

**Comment by AlexanderAltemoeller** [comment]
Update:

- Stylesheet hinzugefügt
- Optik verbessert

@AlexanderAltemoeller @NilsAffing @Jack5496

**Comment by Jack5496** [comment]
Updated: Forschung für Präsi komplett,
nun wieder hier

**Comment by Jack5496** [comment]
ToDo:
- Gebäude vorraussetzung
- Lvl caps
- ID Konflikt vermeiden

**Comment by JulianKniephoff** [comment]
Bitte kleinere, spezifischere issues erstellen und hier verlinken.

Wichtige Informationen aus diesem Issue, die keine Aufgaben sind, bitte ins Wiki übertragen und hier ebenfalls verlinken.

**Comment by Jack5496** [comment]
Alles klar, folgt noch.

Update:
- Forschungen sind vorerst fertig

ToDo:
- Warten auf Stationen Push, für verknüpfung der Voraussetzungen

PS: Machen uns nun an Einheiten ran, welche man erstellen kann

**Comment by AlexanderAltemoeller** [comment]
Wir fügen nun auch hier die Gebäudevorraussetzungen für die einzelnen Forschungen hinzu.

@AlexanderAltemöller @NilsAffing @Jack5496

**Comment by AlexanderAltemoeller** [comment]
Die entsprechenden Wikiseiten gibt es übrigens hier:
https://github.com/OsnaCS/dbp-game/wiki/Forschung

Und für die Icons:
https://github.com/OsnaCS/dbp-game/wiki/Ingame-icons

**Comment by AlexanderAltemoeller** [comment]
ToDo:

Forschungszeit an das Forschungsgebäude anpassen.

**Comment by AlexanderAltemoeller** [comment]
Die Forschungszeit passt sich nun auch an das Forschungsgebäude an.
Damit ist die grundlegende Implementierung der Forschungen abgeschlossen und dieses Issue kann geclosed werden.
