### ISSUE TITLE
Forschung präsentierbar machen

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#54]

**Comment by fsandfort** [comment]
@AlexanderAltemoeller @NilsAffing @fsandfort

**Comment by AlexanderAltemoeller** [comment]
Die verbleibende Duration einer Zeit wird nun richtig errechnet und angezeigt (nach wie vor durch neuladen der Seite).
Als nächstes bauen wir einen Parser, welcher durch den string der Forschungsbedingungen iteriert und überprüft, ob eine bestimmte Forschungsstufe weiter ausgebaut werden kann.

@AlexanderAltemoeller @NilsAffing

**Comment by AlexanderAltemoeller** [comment]
@Jack5496 auch dabei gewesen.

Update:
- Timer fertig
- HoverTexte / Infos sehen gut aus
- Vorraussetzungen implementiert
- Vorraussetzungen in HoverTexte drinne
- Zeiten berechnet
- Bilder drinne
- Forschungs Button drinne
- Sofort Button drinne (Pay2Win!!!)
- StyleSheets

ToDo:
- ToolTips via Messages
- Ressourcen sollen abgezogen werden

**Comment by Jack5496** [comment]
Update:
-ToolTips via Messages
-Lvl getter Methode für andere Anwendungen

ToDo: Ressourcen sollen abgezogen werden

PS: Ressourcen abzug kommt nicht mehr in die Präsi

**Comment by Jack5496** [comment]
Weitere updated in dem alten Issue

=CLOSED=
