### ISSUE TITLE
Rangliste präsentierbar machen

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#55]

**Comment by fsandfort** [comment]
@AlexanderAltemoeller @NilsAffing @fsandfort

**Comment by JulianKniephoff** [comment]
Ist dieses issue jetzt noch wichtig?

**Comment by AlexanderAltemoeller** [comment]
Die Rangliste funktioniert.
Dieses Issue kann somit geschlossen werden.
