### ISSUE TITLE
Stationen mit Upgrades präsentierbar machen

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#56]

**Comment by MarenSteinkamp** [comment]
@heburke @MarenSteinkamp @pkechlo @onienhüser

**Comment by Jack5496** [comment]
habe mich dazu getan @Jack5496

**Comment by Jack5496** [comment]
Haben dafür Resourcen sammelbar gemacht, um damit zahlen zu können. Gesammeltes wird nach Formel berechnet.

**Comment by pkechlo** [comment]
Haben das Layout für die Stationenseite mit Bildern fertig. seed.rb wurde angelegt.
Kümmern uns jetzt um eine User-Ship-Station Verbindung.
@onienhueser @pkechlo

**Comment by pkechlo** [comment]
- Ship-Station Verbindung steht

TO-DO:
- User-Ship Verbindung erstellen
- Upgrade Button erstellen
- Beschreibung für Stationen per Tooltip

**Comment by MarenSteinkamp** [comment]
- User-Ship Verbindung steht
@MSteinkamp @heburke

**Comment by pkechlo** [comment]
StationLayout ist auf dem Master. @onienhueser @pkechlo

**Comment by heburke** [comment]
Layout wurde eingefügt und auch auf Schiffe angewendet #58

**Comment by pkechlo** [comment]
- StationLayout an SciencesLayout angepasst: pull request hotfix stationlayout
- Tooltips eingefügt und schon auf dem Master

ToDo:
- Upgrade-Button (zur Präsentation nicht fertig)

**Comment by JulianKniephoff** [comment]
Bitte in kleinere, spezifische Issues aufteilen und diese hier verlinken.

**Comment by pkechlo** [comment]
Upgrade Button und Upgrades für Stationen ist hier. #102

**Comment by JulianKniephoff** [comment]
Okay, ist das dann alles?

**Comment by pkechlo** [comment]
Die hier angestrebten Aufgaben waren heute Morgen zur Präsentation fast alle fertig. Es blieb nur der Upgrade Button übrig welchen wir jetzt bei #102 haben.
Dieses issue könnte also auch geschlossen werden.

**Comment by JulianKniephoff** [comment]
:+1:
