### ISSUE TITLE
Nutzerverwaltung präsentierbar machen

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#57]

**Comment by ChristianReinhard** [comment]
CSS müsste noch für die entsprechenden Seiten eingebaut werden können, sofern morgen Di. 08.09.15 alle branches gemergt sind kann man sich der Sache annähern. @krueter-uos ? @ChristianReinhard

**Comment by ChristianReinhard** [comment]
@JulianKniephoff abgeschlossen.
