### ISSUE TITLE
Rudimentäres Schiffs-Management

### ISSUE THREAD

**Issue by JulianKniephoff** [OsnaCS/dbp-game#58]

**Comment by MarenSteinkamp** [comment]
@heburke @MarenSteinkamp

**Comment by MarenSteinkamp** [comment]
Update:
Gemacht: Rohstoffe werden entsprechend des Levels der Scanner erhöht
To Do: 
- Ansicht für Rohstoffe
- neues Schiff kaufen

**Comment by heburke** [comment]
DONE: 
- neues Schiff erstellen/kaufen (keine DELETE funktion)

**Comment by JulianKniephoff** [comment]
Bitte in kleinere, spezifischere Issues für die Teile, die jetzt noch offen sind, aufteilen und hier verlinken.

**Comment by heburke** [comment]
Alles erledigt. 
Button bleibt wie er ist.
