### ISSUE TITLE
Controller absichern um min. ein Schiff zu besitzen

### ISSUE THREAD

**Issue by ChristianReinhard** [OsnaCS/dbp-game#88]
Bitte fügt dies:

```ruby
if current_user.activeShip == nil 
    redirect_to :controller => 'ships', :action => 'new'
end
```
in all eure Controller actions ein, damit sofern kein Ship ausgewählt ist ein neues erstellt wird, welches automatisch zu eurem aktuellen wird.

**Comment by ChristianReinhard** [comment]
Villeicht wäre es besser diese Prüfung in den AppController einzubauen und dann mit before_actions aufgerufen werden.

**Comment by JulianKniephoff** [comment]
Ja, das wäre in der tat besser. Jemand möge es tun.

Noch besser wäre aber vielleicht, wenn schon im Model sichergestellt wird, dass dieser Fall neimals eintritt.

**Comment by ChristianReinhard** [comment]
@MarenSteinkamp kennt sich in dem Model aus

**Comment by heburke** [comment]
DONE
- Wurde in AppControler eingebaut.
