### ISSUE TITLE
Erweiterung Schiffe

### ISSUE THREAD

**Issue by heburke** [OsnaCS/dbp-game#94]
Kosten für das kaufen von Schiffen, sitzen der grenze von möglichen Schiffe (9) und implementieren einer Fehlerbehandlung falls SchiffsID = `Nil`

**Comment by heburke** [comment]
@heburke @MarenSteinkamp

DONE

**Comment by heburke** [comment]
TODO:
- Schiffe verkaufen
- Layout für buttons (buy, sell, back,....)

**Comment by JulianKniephoff** [comment]
Das klingt auch nach mehreren Aufgaben. Bitte ein Issue pro Teilaufgabe anlegen. ;)

**Comment by heburke** [comment]
Layout für buttons erledigt.
Topic Somit closed.

Schiffe verkaufen: #111

**Comment by JulianKniephoff** [comment]
:+1:
