### ISSUE TITLE
Implementation Anlagen

### ISSUE THREAD

**Issue by fsandfort** [OsnaCS/dbp-game#95]
@fsandfort @fizzule

**Comment by JulianKniephoff** [comment]
Okay, was ist hier genau zu tun?

Bitte spezifischere Issues erstellen, sobald das klar ist.

**Comment by fizzule** [comment]
Exact das gleiche wie bei forschung.
Also alles nachprogrammieren und dann an Anlagen anpassen.
also keine Level, andere formeln für die diversen Berechnungen, sowie weitere Datenbank Felder für das Kampfsystem.
Außerdem anderes Layout und andere Art des erforschens

**Comment by JulianKniephoff** [comment]
:+1:

**Comment by fsandfort** [comment]
To do:
-Damagetypes, Hülle und Angriff ergänzen
- Conditions (Gebäude und Forschung) einfügen
- Methode "is_hidden"
- 5 Aufträge gleichzeitig
@fsandfort @fizzule

**Comment by fizzule** [comment]
5 Auträge gleichzeitig wird ausgelagert in die Bauliste
Es muss noch 3 mal für die werte Damagetype, Hülle und Angriff migriert werden und diese Daten in den seeds ergänzt werden

**Comment by AndreasSchroeder** [comment]
#168 Wir benötigen noch die Werte der Anlagen für die Berechnung.

**Comment by AndreasSchroeder** [comment]
#198 Seeds und Fehlende Spalten sind hinzugefügt

**Comment by JulianKniephoff** [comment]
Ist das dann jetzt fertig?
