### ISSUE TITLE
Echtzeit Ressourcen Update

### ISSUE THREAD

**Issue by Jack5496** [OsnaCS/dbp-game#96]
ToDo:
- automatisches update der Ressourcen ohne neuladen der Seite

**Comment by Jack5496** [comment]
@Jack5496 @AlexanderAltemoeller @NilsAffing

**Comment by heburke** [comment]
@heburke @MarenSteinkamp

Automatisches aktualisiert der DatenbankWerte beim aktualisieren der Seite. DONE

**Comment by ChristianReinhard** [comment]
Wurde durch #97 eingebunden. PR dafür wird noch erstellt.
