### ISSUE TITLE
Notification Center - Einbindung

### ISSUE THREAD

**Issue by krueter-uos** [OsnaCS/dbp-game#97]
Einbindung der Notifications, gelesen aus der Datenbank.
Anzeige der neuen Notifications.

@krueter-uos @ChristianReinhard

**Comment by ChristianReinhard** [comment]
Resourcen werden auch automatisch geupdetet (alle 5 sekunden).

**Comment by JulianKniephoff** [comment]
Ist das also erledigt?

**Comment by ChristianReinhard** [comment]
@JulianKniephoff PR kommt gleich
